#! /bin/bash
# Living on the edge!

CLIENT_DIR="rabbitmq-erlang-client"
SERVER_DIR="rabbitmq-server"
CODEGEN_DIR="rabbitmq-codegen"

function git_clone {
	cd contrib
	echo "==> $1 (get-deps)"
	git clone "https://github.com/rabbitmq/$1.git"
	cd ..
}

function git_update {
	if [ -d contrib/$1 ]
	then
		cd contrib/$1
		echo "==> $1 (update-deps)"
		git pull
		cd ../..
	else
		git_clone $1
	fi
}

function delete {
	echo "==> $1 (delete-deps)"
	rm -rf contrib/$1
}

function pre_compile {
	if [ ! -d ebin ]; then
		mkdir ebin
	fi

	if [ ! -d priv ]; then
		mkdir priv
	fi

	make -C contrib/rabbitmq-erlang-client

	# hack for reltool
	if [ ! -d oacd_hop ]; then
		mkdir oacd_hop
		ln -sf ../ebin oacd_hop/ebin
		ln -sf ../src oacd_hop/src
		ln -sf ../include oacd_hop/include
		ln -sf ../priv oacd_hop/priv
		ln -sf ../deps oacd_hop/deps
	fi

	# record what commit/version the rep is at
	COMMIT=""
	if [ -d ".git" ]
	then
		COMMIT=`git log -1 --pretty=format:%H`
	fi
	if [ -e "include/commit_ver.hrl" ] && [ ! $COMMIT ]
	then
		exit 0
	else
		if [ ! COMMIT ]
		then
			COMMIT="undefined"
		else
			COMMIT="\"$COMMIT\""
		fi
	fi
	if [ ! -d include ]; then
		mkdir include
	fi
	echo "%% automatically generated by precompile script.  Editing means this
%% will just be overwritten.

-define(COMMIT, $COMMIT)." > include/commit_ver.hrl
}

if [ ! -d contrib ]
then
	mkdir contrib
fi

case $1 in
	"get")
		git_clone $CODEGEN_DIR
		git_clone $CLIENT_DIR
		git_clone $SERVER_DIR;;
	"update")
		git_update $CODEGEN_DIR
		git_update $CLIENT_DIR
		git_update $SERVER_DIR;;
	"delete")
		delete $CODEGEN_DIR
		delete $CLIENT_DIR
		delete $SERVER_DIR;;
	"pre_compile")
		pre_compile;;
esac
