#! /bin/bash
rm -rf oacd_hop
mkdir oacd_hop
./rebar compile
cp -R ebin include priv oacd_hop
mkdir oacd_hop/deps
cp -R deps/amqp_client deps/gen_bunny deps/meck deps/rabbit_common oacd_hop/deps

for file in oacd_hop/deps/*
do
	if [ -d $file ]
		then rm -rf $file/.git*
	fi
done
